version: "3.1"

services:
  v2raya:
    image: mzz2017/v2raya:latest
    container_name: v2raya
    restart: always
    privileged: true
    network_mode: host
    volumes:
      - /etc/v2raya:/etc/v2raya
      - /lib/modules:/lib/modules:ro
      - /etc/resolv.conf:/etc/resolv.conf
    environment:
      TZ: Asia/Shanghai
      V2RAYA_ADDRESS: 0.0.0.0:2017

  portainer:
    image: gwq5210/portainer:latest
    container_name: portainer
    command: --tlsskipverify
    restart: always
    # network_mode: host
    ports:
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKER_NAS_DATA_DIR}/portainer:/data
    environment:
      TZ: Asia/Shanghai

  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    network_mode: 'host'
    volumes:
      - ${DOCKER_NAS_CONF_DIR}/jellyfin:/config
      - ${DOCKER_NAS_DATA_DIR}/jellyfin/cache:/cache
      - ${DOCKER_NAS_DATA_DIR}/jellyfin/media:/media
    restart: always
    privileged: true
    environment:
      TZ: Asia/Shanghai
    deploy:
      resources:
        reservations:
          devices:
            - driver: "nvidia"
              count: 1
              capabilities: [gpu]