version: "3.1"

services:
  gwq5210_v2raya:
    image: mzz2017/v2raya:latest
    container_name: gwq5210_v2raya
    restart: always
    volumes:
      - ./v2raya/conf:/etc/v2raya
    ports:
      - "2017:2017"
      - "20170-20172:20170-20172"
    environment:
      TZ: Asia/Shanghai
