version: "3.1"

services:
  v2raya:
    image: mzz2017/v2raya:latest
    container_name: v2raya
    restart: always
    privileged: true
    network_mode: host
    volumes:
      - /etc/v2raya:/etc/v2raya
      - /lib/modules:/lib/modules:ro
      - /etc/resolv.conf:/etc/resolv.conf
    environment:
      TZ: Asia/Shanghai
      V2RAYA_ADDRESS: 0.0.0.0:2017

  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    network_mode: 'host'
    volumes:
      - ${DOCKER_NAS_CONF_DIR}/jellyfin:/config
      - ${DOCKER_NAS_DATA_DIR}/jellyfin/cache:/cache
      - ${DOCKER_NAS_DATA_DIR}/jellyfin/media:/media
    restart: always
    privileged: true
    environment:
      TZ: Asia/Shanghai

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - WEBUI_PORT=6880
    volumes:
      - ${DOCKER_NAS_HOME}/qbittorrent/conf:/config
      - ${DOCKER_NAS_DOWNLOADS}:/downloads
    ports:
      - 6880:6880
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
