version: '3.1'

services:
  agent:
    image: gwq5210/portainer_agent:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    environment:
      TZ: Asia/Shanghai
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: gwq5210/portainer:latest
    command: -H tcp://tasks.agent:9001 --tlsskipverify"
    ports:
      - "9443:9443"
    volumes:
      - ${DOCKER_NAS_DATA_DIR}/portainer:/data
    depends_on:
      - agent
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    environment:
      TZ: Asia/Shanghai
